-- ================================================================
-- EDIT A BYE (or turn any match into one) via update_match_teams
--
-- The Fixtures tab already lets an admin edit a match's teams and leave
-- "Team B" blank — the TeamSelect placeholder literally says "TBD / bye",
-- and the UI shows a "Bye" badge once status = 'completed' and
-- team_b_id is null (FixturesTab.tsx). But update_match_teams()
-- (tournaments.sql) never actually implemented that: leaving team B
-- blank just reset the match to 'unscheduled' with only team_a_id set —
-- and record_match_result() requires both teams, so that match could
-- never be completed or advance a winner. In practice, editing a
-- generated bye (to swap which team got it) permanently broke that
-- bracket slot.
--
-- Fix: when p_team_b_id is null, update_match_teams now completes the
-- match as a bye — team_a_id advances immediately with no score, same
-- as the byes build_knockout_bracket() creates — and propagates the
-- winner to next_match_id, same as a real result would. Supplying a
-- team_b_id still behaves as before (reset to unscheduled, pending a
-- real result). Downstream matches are unwound first via
-- reset_downstream_from() exactly as already happened, so re-editing a
-- bracket mid-tree stays consistent either way.
--
-- Run AFTER: tournaments.sql (update_match_teams, reset_downstream_from,
-- propagate_match_winner, tournament_match_audit).
-- Idempotent. Not destructive to matches that already have a result —
-- FORBIDDEN/MATCH_ALREADY_DONE checks are unchanged; this only changes
-- what happens once the caller is already allowed to edit the match.
-- ================================================================

create or replace function public.update_match_teams(p_match_id uuid, p_team_a_id uuid, p_team_b_id uuid default null)
returns public.tournament_matches
language plpgsql security definer set search_path = public as $$
declare v_before public.tournament_matches; v_match public.tournament_matches; v_t public.tournaments; v_was_done boolean;
begin
  select * into v_match from public.tournament_matches where id = p_match_id for update;
  if not found then raise exception 'MATCH_NOT_FOUND'; end if;
  v_before := v_match;
  select * into v_t from public.tournaments where id = v_match.tournament_id;
  if not (
    public.is_tournament_organizer(v_t)
    or public.has_venue_access(v_t.venue_id, 'manager')
    or public.is_super_admin()
  ) then
    raise exception 'FORBIDDEN';
  end if;

  if not exists (
    select 1 from public.tournament_teams
    where id = p_team_a_id and tournament_id = v_match.tournament_id and status = 'confirmed'
  ) then
    raise exception 'TEAM_NOT_FOUND';
  end if;

  if p_team_b_id is not null then
    if p_team_a_id = p_team_b_id then raise exception 'SAME_TEAM'; end if;
    if not exists (
      select 1 from public.tournament_teams
      where id = p_team_b_id and tournament_id = v_match.tournament_id and status = 'confirmed'
    ) then
      raise exception 'TEAM_NOT_FOUND';
    end if;
  end if;

  v_was_done := v_match.status in ('completed', 'walkover');
  if v_was_done and v_match.next_match_id is not null then
    perform public.reset_downstream_from(p_match_id);
  end if;

  if p_team_b_id is null then
    -- Bye: team_a_id advances immediately, same as a generated bye.
    update public.tournament_matches set
        team_a_id = p_team_a_id, team_b_id = null,
        status = 'completed', winner_team_id = p_team_a_id,
        score_a = null, score_b = null, score_a_et = null, score_b_et = null,
        score_a_pens = null, score_b_pens = null
      where id = p_match_id returning * into v_match;
  else
    update public.tournament_matches set
        team_a_id = p_team_a_id, team_b_id = p_team_b_id,
        status = case when v_was_done then 'unscheduled' else status end,
        score_a = case when v_was_done then null else score_a end,
        score_b = case when v_was_done then null else score_b end,
        score_a_et = case when v_was_done then null else score_a_et end,
        score_b_et = case when v_was_done then null else score_b_et end,
        score_a_pens = case when v_was_done then null else score_a_pens end,
        score_b_pens = case when v_was_done then null else score_b_pens end,
        winner_team_id = case when v_was_done then null else winner_team_id end
      where id = p_match_id returning * into v_match;
  end if;

  insert into public.tournament_match_audit (match_id, tournament_id, changed_by, change_type, old_value, new_value)
  values (v_match.id, v_match.tournament_id, auth.uid(), 'teams', to_jsonb(v_before), to_jsonb(v_match));

  if p_team_b_id is null and v_match.next_match_id is not null then
    perform public.propagate_match_winner(p_match_id, p_team_a_id);
  end if;

  return v_match;
end;
$$;
grant execute on function public.update_match_teams(uuid,uuid,uuid) to authenticated;

-- ── DONE ────────────────────────────────────────────────────────────
